spring.application.name=developer-management-api

spring.datasource.url=jdbc:postgresql://localhost:5332/developer_management
spring.datasource.username=daviddevgado
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

logging.level.com.daviddevgado.developer_management_api.service.impl=DEBUG
logging.level.com.daviddevgado.developer_management_api=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n